### ISSUE TITLE
Create a leaderboard that displays below instructions within /app

### ISSUE THREAD

**Issue by zaycation** [zaycation/jewel-jack#8]
On the main game screen, there is the game itself, then below it, there is the instructions. Below the instructions, please create some sort of table/leaderboard system that allows people to post their wins and losses once they win 1 game. Those with the best ratio (must have minimum of 3 games played) should be shown at the top of the leaderboard. The prompt should be with sweetalert2 (same dependency used to display win/loss modal). Let the user add their custom display name to display as well with their win/loss.

**Comment by ting-c** [comment]
Hi, I would like to help you on this. I had a brief look at the codebase and am I right to assume the names of the players are to be stored in react state for now?

**Comment by zaycation** [comment]
@ting-c storing in state is perfectly fine for now! Thank you so much for wanting to help.

We are working on setting up the database with mongodb soon. When trying to run the app on your device, use "npm run dev" in the terminal to run the app with the nodejs server.
